"""Canonical Phase 1 default values for engine and RL environment configuration.

Single source of truth for world size, cargo limits, reward coefficients,
observation scales, and default component names. Import-time validation fails
fast; copy with ``dataclasses.replace`` and never mutate in place.

**Last updated:** September 1, 2026

**Contains:** ``DEFAULT_ENGINE_CONFIG``, ``DEFAULT_ENVIRONMENT_CONFIG``.

**Defaults include:** 32×32 map, 12 kg cargo, 0.5 kg scan samples, 2 kg ice
extract, shaped/sparse reward weights, ``local`` observation + ``discrete`` action.

**See also:** :mod:`aresim.config` (config shapes),
:mod:`aresim.registry.create_default_registry` (built-in component names).
"""

from types import MappingProxyType

from .config import (
    ActionConfig,
    EngineConfig,
    EnvironmentConfig,
    GenerationConfig,
    InitialConfig,
    LandingConfig,
    LifeSupportConfig,
    ObservationConfig,
    PayloadConfig,
    PowerConfig,
    ReplayConfig,
    RewardConfig,
    RewardProfileConfig,
    ServiceConfig,
    WarningConfig,
    WorldConfig,
)
from .types import ActionType, TerrainType, WeatherState


DEFAULT_ENGINE_CONFIG = EngineConfig(
    world=WorldConfig(
        size=32,
        default_seed=1447,
        seed_min=0,
        seed_max=99_999,
        steps_per_sol=48,
        start_time_minutes=8 * 60,
        minutes_per_step=18,
        weather_cycle=(WeatherState.CLEAR, WeatherState.DUSTY, WeatherState.DUST_FRONT, WeatherState.COLD_NIGHT),
    ),
    generation=GenerationConfig(
        ice_center_count=3,
        ore_center_count=4,
        crater_center_count=3,
        ice_radius=5.6,
        ore_radius=4.8,
        ore_ridge_radius=8.8,
        crater_radius=3.9,
        ridge_y_min=5,
        ridge_y_span=12,
        dune_offset_min=8,
        dune_offset_span=12,
    ),
    landing=LandingConfig(
        radius=2,
        retry_count=8,
        retry_seed_offset=997,
        fallback_seed_offset=7919,
        safe_margin=5,
        max_ice=0.2,
        max_roughness=0.42,
        min_height=0.28,
        max_height=0.72,
        sanitized_height=0.46,
        sanitized_roughness=0.16,
        max_pad_roughness=0.22,
        max_pad_dust=0.28,
    ),
    initial=InitialConfig(
        rover_battery=100,
        rover_health=91,
        habitat_health=92,
        solar_health=88,
        battery_health=94,
        storage_health=96,
        initial_power_generated=18,
        initial_power_consumed=12,
        water_min=80,
        water_range=50,
        oxygen_min=120,
        oxygen_range=70,
        livability=24,
        dust_min=0.22,
        dust_range=0.32,
    ),
    payload=PayloadConfig(
        capacity_kg=12,
        scan_sample_kg=0.5,
        ice_extraction_kg=2,
        ice_channel_reduction=0.62,
        extract_min_ice_signal=0.25,
        unload_water_per_ice=1.8,
        unload_oxygen_per_ice=0.8,
        unload_livability_per_ice=0.08,
    ),
    power=PowerConfig(
        base_load=6.5,
        habitat_load=4.2,
        storage_load=1.1,
        charger_load=1.6,
        solar_panel_output=42,
        weather_generation_factor=MappingProxyType({
            WeatherState.CLEAR: 1.18,
            WeatherState.DUSTY: 0.72,
            WeatherState.DUST_FRONT: 0.48,
            WeatherState.COLD_NIGHT: 0.22,
            WeatherState.SEVERE_STORM: 0.36,
        }),
        dust_generation_multiplier=0.42,
        dust_generation_floor=0.3,
        deficit_battery_cap=1.6,
        deficit_battery_rate=0.055,
        wait_charge_per_kw=0.85,
        wait_max_charge=18,
        pad_charge_per_kw=0.25,
        pad_max_charge=4,
    ),
    service=ServiceConfig(
        dust_threshold=0.78,
        health_threshold=62,
        power_margin_threshold=-8,
        power_dust_threshold=0.55,
        service_radius=2,
        serviced_dust=0.08,
        restored_structure_health=100,
        weather_damage=MappingProxyType({
            WeatherState.CLEAR: 0.015,
            WeatherState.DUSTY: 0.045,
            WeatherState.DUST_FRONT: 0.12,
            WeatherState.COLD_NIGHT: 0.015,
            WeatherState.SEVERE_STORM: 0.12,
        }),
        weather_dust_delta=MappingProxyType({
            WeatherState.CLEAR: -0.025,
            WeatherState.DUSTY: 0.035,
            WeatherState.DUST_FRONT: 0.07,
            WeatherState.COLD_NIGHT: -0.01,
            WeatherState.SEVERE_STORM: 0.08,
        }),
        dust_damage_rate=0.025,
        dust_floor=0.08,
        dust_ceiling=0.92,
    ),
    life_support=LifeSupportConfig(
        water_base_drain=0.07,
        water_livability_rate=0.0018,
        water_dust_rate=0.035,
        oxygen_base_drain=0.09,
        oxygen_livability_rate=0.0022,
        oxygen_deficit_rate=0.012,
        livability_base_decay=0.03,
        empty_reserve_penalty=0.5,
        power_deficit_cap=0.3,
        power_deficit_rate=0.019,
        service_bonus=0.22,
        build_bonus=1.1,
        low_battery_health_threshold=15,
        critical_battery_health_threshold=5,
        normal_health_decay=0.025,
        low_battery_health_decay=0.25,
        critical_battery_health_decay=1.2,
    ),
    action=ActionConfig(
        base_drain=MappingProxyType({
            ActionType.MOVE: 0.32,
            ActionType.SCAN: 0.24,
            ActionType.EXTRACT: 0.82,
            ActionType.BUILD: 1.05,
            ActionType.SERVICE: 0.52,
            ActionType.UNLOAD: 0.18,
            ActionType.WAIT: 0.0,
            ActionType.INVALID: 0.16,
            ActionType.EVENT: 0.16,
        }),
        action_load=MappingProxyType({
            ActionType.MOVE: 0.15,
            ActionType.SCAN: 0.35,
            ActionType.EXTRACT: 1.4,
            ActionType.BUILD: 1.8,
            ActionType.SERVICE: 0.8,
            ActionType.UNLOAD: 0.25,
            ActionType.WAIT: 0.0,
            ActionType.INVALID: 0.0,
            ActionType.EVENT: 0.0,
        }),
        action_stress=MappingProxyType({
            ActionType.MOVE: 0.02,
            ActionType.SCAN: 0.08,
            ActionType.EXTRACT: 0.58,
            ActionType.BUILD: 0.66,
            ActionType.SERVICE: 0.28,
            ActionType.UNLOAD: 0.04,
            ActionType.WAIT: 0.02,
            ActionType.INVALID: 0.02,
            ActionType.EVENT: 0.02,
        }),
        terrain_stress=MappingProxyType({
            TerrainType.BUILD_PAD: 0.05,
            TerrainType.REGOLITH: 0.14,
            TerrainType.ICE: 0.30,
            TerrainType.ROCK: 0.38,
            TerrainType.DUNE: 0.55,
            TerrainType.RIDGE: 0.82,
            TerrainType.CRATER: 0.0,
        }),
        weather_stress=MappingProxyType({
            WeatherState.CLEAR: -0.06,
            WeatherState.DUSTY: 0.22,
            WeatherState.DUST_FRONT: 0.48,
            WeatherState.COLD_NIGHT: 0.28,
            WeatherState.SEVERE_STORM: 0.62,
        }),
        roughness_stress_rate=0.45,
        cell_dust_stress_rate=0.22,
        cargo_stress_rate=0.012,
        global_dust_stress_rate=0.28,
        stress_exponent_rate=0.32,
        habitat_build_steps=10,
        build_water_cost=1.4,
        build_oxygen_cost=0.7,
        habitat_health_gain=4,
        extract_ice_priority_weight=4,
    ),
    warning=WarningConfig(
        water_reserve=25,
        oxygen_reserve=25,
        rover_battery=18,
        rover_health=35,
        livability=16,
    ),
    reward=RewardConfig(
        energy_rate=0.08,
        normal_traversal=0.01,
        pad_traversal=0.002,
        safe_move=0.01,
        hazardous_move=-0.08,
        scan_information=1.1,
        scan_exploration=0.25,
        ice_resource_per_kg=0.42,
        ore_resource_per_kg=0.2,
        build_infrastructure=1.8,
        build_livability=0.75,
        service_base=0.35,
        service_needed=1.2,
        service_efficiency=0.35,
        ice_delivery_per_kg=0.5,
        ore_delivery_per_kg=0.4,
        sample_delivery_per_kg=0.3,
        unload_logistics=0.4,
        wait_surplus=0.25,
        wait_deficit=-0.15,
        invalid=-1.5,
        invalid_safety=-0.3,
    ),
    replay=ReplayConfig(
        schema_version="aresim.gameplay.v1",
        app_version="0.1.0",
        checkpoint_interval=10,
        max_upload_bytes=25_000_000,
    ),
)

DEFAULT_ENGINE_CONFIG.validate()


DEFAULT_ENVIRONMENT_CONFIG = EnvironmentConfig(
    engine=DEFAULT_ENGINE_CONFIG,
    scenario_id="phase1_default_v1",
    observation="local",
    observation_config=ObservationConfig(
        window_size=8,
        max_objectives=8,
        power_scale=50,
        water_scale=130,
        oxygen_scale=190,
    ),
    action="discrete",
    reward="shaped_train",
    reward_config=RewardProfileConfig(
        mission_success=10,
        terminal_failure=-5,
        objective_progress=2,
        new_scan=0.10,
        ice_delivered=0.50,
        samples_delivered=0.20,
        build_progress=0.50,
        service_recovery=0.25,
        hazard_damage=-1,
        energy_used=-0.05,
        invalid_action=-0.10,
        time_cost=-0.001,
        clip_min=-2,
        clip_max=2,
    ),
    task="open_exploration",
)

DEFAULT_ENVIRONMENT_CONFIG.validate()
